# Generated by Django 5.2.15 on 2026-08-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags that are not in the Skills list e.g. "Deep Links, ASGI"', max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('framework', 'Framework'), ('database', 'Database'), ('infra', 'Infrastructure'), ('service', 'Third-party Service'), ('language', 'Language'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
